*** Settings ***
Documentation    this file contains the common Variables


*** Variables ***
${valid_username}             Admin
${valid_password}             admin123
${employee_first_name}        Mostafa
${employee_last_name}         Khalid
${employee_id}                1141
${id_for_search}              0259
${vacancy_name}               WN
${leave_date_start}           27
${leave_date_end}             28
${SCREENSHOT_DIR}             C:/Users/14192/HelloPython/robot_test_project/screenshots
